### ISSUE TITLE
Provide Class for HTTP Signature utilities that require an Actor Key

### ISSUE THREAD

**Issue by jojobii-arks** [musakui/fedi#3]
## Issue

- Currently, utilities within `hs` that utilize an Actor Key rely on mutable variables that are declared on import. 
- I'm unsure what the paradigm is called, but having an "`HttpSignatureClient`" that can be instantiated via "`createHttpSignatureClient`" would be pretty handy, and could enable use cases such as being able to sign with different keys from the same runtime. 

## Notes

- This would require an export for each signing method (node, browser).
  - It's a bit of a stretch, but maybe all of those constructors can be wrapped into a single function that can utilize the necessary Crypto method for signing that is implied from the runtime OR defined manually via configuration argument

**Comment by randName** [comment]
ah, it's a code style that helps with treeshaking (especially for singletons). But I think it doesn't help much with the current code and wrapping them up in a class makes sense.

(evidently my use case was too focused on single user instances and completely forgot that normal servers need to sign for different users 😅)

**Comment by randName** [comment]
The signer info is now encapsulated in the `Signer` class. in the future if there are other runtimes with different signing utilities the `CoreSigner` class can be extended.

```js
import { sendRequest, Signer } from '...'
const res = await sendRequest(req, new Signer(keyId, key))
```
