### ISSUE TITLE
Update activitypub-models link

### ISSUE THREAD

**Issue by siranweb** [musakui/fedi#7]
Firstly, thanks for adding my package to this repo :)

Want to ask you to update the [activitypub-js/activitypub-models](https://github.com/activitypub-js/activitypub-models) link from readme, because it's archived now. I made another package [SiranWeb/activitypub-types](https://github.com/SiranWeb/activitypub-types), which is based on previous one. Probably it will be useful for people who needs to implement models logic by themselves. 

Thank you!

**Comment by randName** [comment]
i stopped following the space very closely so thanks for the update!
